# Generated by Django 4.2.5 on 2023-10-07 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0003_alter_vote_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'default_permissions': ['add', 'delete']},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'default_permissions': [], 'permissions': [('vote_answer', 'Can vote answer'), ('vote_question', 'vote_question')]},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('owner', 'question', 'answer')},
        ),
        migrations.CreateModel(
            name='Approve',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questions.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('approve_answer', 'can approve answer')],
                'default_permissions': [],
            },
        ),
    ]
