# Generated by Django 4.2.5 on 2023-09-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Lecture', 'Lecture'), ('Seminar', 'Seminar'), ('Workshop', 'Workshop'), ('Lab', 'Lab'), ('Tutorial', 'Tutorial'), ('Discussion Group', 'Discussion Group'), ('Project Presentation', 'Project Presentation'), ('Study Group', 'Study Group'), ('Examination', 'Examination'), ('Research Seminar', 'Research Seminar'), ('Conference', 'Conference')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('english_name', models.CharField(max_length=30)),
                ('arabic_name', models.CharField(max_length=30)),
                ('credit_hours', models.PositiveSmallIntegerField()),
            ],
            options={
                'default_permissions': ['add', 'delete', 'view', 'change'],
            },
        ),
        migrations.CreateModel(
            name='CourseGPA',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('building', models.CharField(max_length=30)),
                ('floor', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
                ('end_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.activity')),
                ('end_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_period', to='academic.period')),
                ('groups', models.ManyToManyField(to='academic.group')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.location')),
                ('start_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_period', to='academic.period')),
            ],
        ),
    ]
