# Generated by Django 4.2.5 on 2023-09-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='assignments',
            field=models.ManyToManyField(blank=True, to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.course'),
        ),
        migrations.AddField(
            model_name='coursegpa',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.course'),
        ),
        migrations.AddField(
            model_name='coursegpa',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.term'),
        ),
    ]
