# Generated by Django 4.2.5 on 2023-10-07 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_location_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'default_permissions': ['add', 'delete', 'view', 'change']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'default_permissions': ['add', 'delete', 'view', 'change'], 'permissions': [('view_own_courses', 'can view own courses'), ('enroll_course', 'can enroll course'), ('unenroll_course', 'can_unenroll_course')]},
        ),
        migrations.AlterModelOptions(
            name='coursegpa',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'default_permissions': ['add', 'delete', 'change']},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'default_permissions': ['add', 'delete', 'change']},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'default_permissions': ['add', 'delete', 'change']},
        ),
    ]
