# Generated by Django 4.2.5 on 2023-10-07 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'default_permissions': ['add', 'delete', 'view', 'change']},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'default_permissions': ['add', 'delete', 'view', 'change']},
        ),
    ]
