# Generated by Django 4.2.5 on 2023-09-28 14:30

import campus.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('image', campus.models.AutoNameImageField(null=True, upload_to='announcements/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('delete_own_announcement', 'Can delete own announcement'), ('change_own_announcement', 'Can change own announcement')],
                'default_permissions': ['add', 'view', 'delete', 'change'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=7)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.announcement')),
            ],
            options={
                'permissions': [('delete_own_reaction', 'can delete own reaction')],
                'default_permissions': ['add'],
            },
        ),
    ]
