# Generated by Django 4.2.5 on 2023-10-07 20:23

import campus.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_alter_announcement_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reaction',
            options={'default_permissions': [], 'permissions': [('react_announcement', 'can react announcement')]},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=campus.models.AutoNameImageField(blank=True, null=True, upload_to='announcements/'),
        ),
    ]
