# Generated by Django 4.2.5 on 2023-09-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'default_permissions': ['add', 'delete']},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'default_permissions': ['add', 'delete', 'view']},
        ),
    ]
