# Generated by Django 4.2.5 on 2023-09-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
