# Generated by Django 4.2.5 on 2023-10-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_student_academic_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetoken',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='googleuser',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'default_permissions': ['add', 'change', 'delete', 'view']},
        ),
        migrations.AlterModelOptions(
            name='studentgroupcourse',
            options={'default_permissions': ['add', 'change', 'delete', 'view']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'default_permissions': ['add', 'change', 'delete', 'view']},
        ),
        migrations.AlterField(
            model_name='googleuser',
            name='google_id',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
