# Generated by Django 4.2.5 on 2023-10-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='platform',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='f',
        ),
    ]
