# Generated by Django 4.2.5 on 2023-10-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_device_platform_delete_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='platform',
        ),
        migrations.AddField(
            model_name='device',
            name='token',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
